### ISSUE TITLE
Improve scheduling and backpressure of Mesos response stream

### ISSUE THREAD

**Issue by cruhland** [mesosphere/mesos-rxjava#13]
In `MesosSchedulerClient.openEventStream()`, there are some comments regarding backpressure and custom schedulers. Investigate how to improve the code so that the comments can be removed.

**Comment by zonybob** [comment]
Thought I'd comment on this rather than creating a new issue.
I am getting the dreaded MissingBackpressureException with my rx-mesos based scheduler.
Where is the right place to chain `.onBackpressureBuffer(...)` ? 
It seems like trying to chain it to the unicastEvents is not going to work since it uses buffer(timespan) which explicitly does not support backpressure.

**Comment by BenWhitehead** [comment]
Fixed in #81
