### ISSUE TITLE
Update to mesos 1.2.0

### ISSUE THREAD

**Issue by PhroZenOne** [mesosphere/mesos-rxjava#79]
I have written a wrapper around this (https://github.com/saiaku-gaming/mesos-scheduler-client) that I use in one of my projects, but now I need to have some extra settings that was introduced in mesos 1.2.0. Are you interested in updating to 1.2.0 or should I fork this project?

**Comment by BenWhitehead** [comment]
Mesos 1.2.0 Still uses protobuf 2.6.x as it's proto backend, so you should be able to explicitly include the new mesos version in your project without the need to update anything in mesos-rxjava itself, and in fact is intentional so that mesos-rxjava doesn't have to be released every time mesos has a new release.

Once mesos switches to proto3 the codecs will likely need to be updated for the new version of protobuf.

In your pom.xml you should be able to do something like this:
```
  <dependency>
    <groupId>com.mesosphere.mesos.rx.java</groupId>
    <artifactId>mesos-rxjava-protobuf-client</artifactId>
    <version>0.1.2</version>
  </dependency>
  <dependency>
    <groupId>org.apache.mesos</groupId>
    <artifactId>mesos</artifactId>
    <version>1.2.0</version>
  </dependency>
```

And that will cause maven to use mesos 1.2.0 instead of 1.0.0

Hope this helps.

**Comment by PhroZenOne** [comment]
Ah, perfect. Then I will do the same and just allow for overriding the dependency version in my little wrapper as well.  By the way, thanks for all the heavy lifting done by this project, I wasn't looking forward for implementing all the http2 stuff myself. :)

Cheers!

**Comment by BenWhitehead** [comment]
Cool, I'm glad you're funding it helpful. Be sure to let us know if you run into any issues.
